"""berkas_sm

Revision ID: ba4df9c863b1
Revises: 
Create Date: 2023-09-14 13:08:23.641181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4df9c863b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surat_masuk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_masuk',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('asal_surat', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('no_surat', mysql.INTEGER(display_width=15), autoincrement=False, nullable=False),
    sa.Column('kode_wilayah', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('tanggal_surat', sa.DATE(), nullable=False),
    sa.Column('tanggal_diterima', sa.DATE(), nullable=False),
    sa.Column('perihal', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('keterangan', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
